# Generated by Django 3.0.2 on 2020-01-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movrotativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movrotativo',
            name='Veiculo',
        ),
    ]
