# Generated by Django 3.0.2 on 2020-01-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mensalista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensalista',
            old_name='Veiculo',
            new_name='veiculo',
        ),
    ]
